### PR TITLE
WIP: feat: Count ETH with WETH balances in InventoryClient

### PR DESCRIPTION
**Pull request by nicholaspai**
Addresses duplicate rebalancing issue where rebalancer doesn't see ETH being wrapped into WETH in time before sending redundant rebalance of ETH to L2

### CODE REVIEW

**Comment by nicholaspai** [comment]
Note to self: can use this token client getNativeBalance method wherever we call GetBalance in the repo

**Comment by nicholaspai** [comment]
Make sure that counting eth only factors in when computing allocation percentages to inform rebalances. We don't want it to be counted in the available weth to be rebalanced though as we can't send eth the same way as we can weth

**Comment by pxrl** [comment]
This one could potentially be tricky, since we don't want to rebalance if ETH + WETH > threshold, but in case of a small WETH shortfall causing a non-fill, we might actually want to ignore the ETH :\ I haven't figured out a clean solution for that.

**Comment by nicholaspai** [comment]
Only count native balance on chains that use eth unlike polygon

**Comment by nicholaspai** [comment]
> This one could potentially be tricky, since we don't want to rebalance if ETH + WETH > threshold, but in case of a small WETH shortfall causing a non-fill, we might actually want to ignore the ETH :\ I haven't figured out a clean solution for that.

One idea would be to change the cross chain outstanding transfers logic to only mark cross chain transfers as finalized (for chains that bridge eth not weth) after the eth gets wrapped. But I'm not sure there's a good event to track

**Pull request closed without merging**
